<?php 

$adminservername = "localhost";
$adminusername = "root";
$adminpassword = "";
$admindbname = "berichtsheft";

$initialisierungservername = "localhost";
$initialisierungusername = "initialisierung";
$initialisierungpassword = "123";
$initialisierungdbname = "berichtsheft";


$ausbilderservername = "localhost";
$ausbilderusername = "ausbilder";
$ausbilderpassword = "123";
$ausbilderdbname = "berichtsheft";

$teilnehmerservername = "localhost";
$teilnehmerusername = "teilnehmer";
$teilnehmerpassword = "123";
$teilnehmerdbname = "berichtsheft";

?>